/**
 * KAAS - Kenya Area Administration System
 * Spreadsheet-backed Apps Script data layer
 */

var SHEET_SCHEMAS = {
  Users: ['ID', 'Username', 'Password', 'FullName', 'Role', 'Phone', 'Status', 'CreatedAt', 'UpdatedAt'],
  Cases: ['ID', 'Type', 'Priority', 'Status', 'ResidentName', 'ResidentIdNumber', 'ResidentPhone', 'ResidentLocation', 'Description', 'CreatedAt', 'UpdatedAt', 'CreatedBy', 'UpdatedBy'],
  Documents: ['ID', 'Category', 'DocumentType', 'ResidentName', 'IDNumber', 'Details', 'FileData', 'CreatedAt', 'UpdatedAt', 'CreatedBy', 'UpdatedBy'],
  ResolvedCases: ['ID', 'Type', 'Priority', 'Status', 'ResidentName', 'ResidentIdNumber', 'ResidentPhone', 'ResidentLocation', 'Description', 'CreatedAt', 'UpdatedAt', 'CreatedBy', 'UpdatedBy'],
  Settings: ['ID', 'OfficeName', 'OfficeAddress', 'Location', 'LogoUrl', 'FooterText', 'SmsNotifications', 'EmailNotifications', 'Theme', 'ApiUrl', 'UpdatedAt', 'UpdatedBy'],
  Announcements: ['ID', 'Type', 'Title', 'Content', 'Category', 'FileData', 'MimeType', 'CreatedAt', 'UpdatedAt', 'CreatedBy', 'UpdatedBy']
};

var DEFAULT_SETTINGS = {
  OfficeName: "Chief's Office",
  OfficeAddress: 'P.O. Box 000 - 00100, Nairobi',
  Location: 'Subcounty Headquarters',
  LogoUrl: '',
  FooterText: 'Official administrative record generated by KAAS.',
  SmsNotifications: true,
  EmailNotifications: true,
  Theme: 'classic'
};

var APP_METADATA = {
  appName: 'KAAS',
  version: '2.0.0'
};

function doGet(e) {
  if (isApiRequest_(e)) {
    return handleApiRequest_(e);
  }
  initializeSheets_();
  
  var template = HtmlService.createTemplateFromFile('index');
  template.scriptUrl = ScriptApp.getService().getUrl();
  
  return template.evaluate()
    .setTitle('KAAS - Kenya Area Administration System')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1.0')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function doPost(e) {
  return handleApiRequest_(e);
}

function onOpen() {
  initializeSheets_();
}

function initializeSheets() {
  return runSafely_(function() {
    initializeSheets_();
    return { success: true, message: 'Sheets and headers created successfully.' };
  });
}

function initializeSheets_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var now = nowIso_();

  ensureSheet_(ss, 'Users');
  ensureSheet_(ss, 'Cases');
  ensureSheet_(ss, 'Documents');
  ensureSheet_(ss, 'ResolvedCases');
  ensureSheet_(ss, 'Settings');
  ensureSheet_(ss, 'Announcements');

  seedUsers_(now);
  seedSettings_(now);
}

function ensureSheet_(ss, sheetName) {
  var headers = SHEET_SCHEMAS[sheetName];
  var sheet = ss.getSheetByName(sheetName);

  if (!sheet) {
    sheet = ss.insertSheet(sheetName);
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    sheet.setFrozenRows(1);
    styleHeader_(sheet, headers.length);
    sheet.autoResizeColumns(1, headers.length);
  } else {
    // Check if headers match or if columns are missing
    var lastCol = Math.max(1, sheet.getLastColumn());
    var currentHeaders = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
    var missing = false;
    
    for (var i = 0; i < headers.length; i++) {
      if (currentHeaders.indexOf(headers[i]) === -1) {
        missing = true;
        break;
      }
    }

    if (missing) {
      if (sheet.getMaxColumns() < headers.length) {
        sheet.insertColumnsAfter(sheet.getMaxColumns(), headers.length - sheet.getMaxColumns());
      }
      sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
      styleHeader_(sheet, headers.length);
      sheet.autoResizeColumns(1, headers.length);
    }
  }
}

function styleHeader_(sheet, headerCount) {
  sheet.getRange(1, 1, 1, headerCount)
    .setFontWeight('bold')
    .setBackground('#1E3A5F')
    .setFontColor('#FFFFFF')
    .setHorizontalAlignment('center');
}

function seedUsers_(timestamp) {
  var users = getRecords_('Users');
  if (users.length > 0) {
    return;
  }

  appendRecord_('Users', {
    ID: 'USR001',
    Username: 'admin',
    Password: 'admin123',
    FullName: 'System Administrator',
    Role: 'chief',
    Phone: '0700000000',
    Status: 'active',
    CreatedAt: timestamp,
    UpdatedAt: timestamp
  });
}

function seedSettings_(timestamp) {
  var settingsSheet = getSheet_('Settings');
  if (settingsSheet.getLastRow() > 1) {
    return;
  }

  writeRecord_('Settings', 2, {
    ID: 'SETTINGS001',
    OfficeName: DEFAULT_SETTINGS.OfficeName,
    OfficeAddress: DEFAULT_SETTINGS.OfficeAddress,
    Location: DEFAULT_SETTINGS.Location,
    LogoUrl: DEFAULT_SETTINGS.LogoUrl,
    FooterText: DEFAULT_SETTINGS.FooterText,
    SmsNotifications: DEFAULT_SETTINGS.SmsNotifications,
    EmailNotifications: DEFAULT_SETTINGS.EmailNotifications,
    Theme: DEFAULT_SETTINGS.Theme,
    UpdatedAt: timestamp,
    UpdatedBy: 'system'
  });
}

function login(username, password) {
  return runSafely_(function() {
    initializeSheets_();

    username = trimString_(username);
    password = trimString_(password);

    if (!username || !password) {
      return { success: false, message: 'Username and password are required.' };
    }

    var users = getRecords_('Users');
    for (var i = 0; i < users.length; i++) {
      var record = users[i];
      if (
        String(record.Username).toLowerCase() === username.toLowerCase() &&
        String(record.Password) === password &&
        String(record.Status || 'active').toLowerCase() !== 'inactive'
      ) {
        var user = mapUserRecordToClient_(record);
        var token = Utilities.getUuid();
        CacheService.getScriptCache().put(token, JSON.stringify(user), 21600);
        return { success: true, user: user, token: token };
      }
    }

    return { success: false, message: 'Invalid login credentials.' };
  });
}

function validateToken(token) {
  initializeSheets_();
  var user = getCachedUser_(token);
  if (!user) {
    return { success: false, message: 'Session expired. Please log in again.' };
  }
  return { success: true, user: user };
}

function logout(token) {
  if (token) {
    CacheService.getScriptCache().remove(token);
  }
  return { success: true, message: 'Logged out successfully.' };
}

function signup(data) {
  return runSafely_(function() {
    initializeSheets_();

    data = data || {};
    var username = trimString_(data.username);
    var password = trimString_(data.password);
    var fullName = trimString_(data.fullName);
    var role = trimString_(data.role) || 'resident';
    var phone = trimString_(data.phone);

    if (!username || !password || !fullName) {
      return { success: false, message: 'Full name, username and password are required.' };
    }

    if (password.length < 6) {
      return { success: false, message: 'Password must be at least 6 characters.' };
    }

    var users = getRecords_('Users');
    for (var i = 0; i < users.length; i++) {
      if (String(users[i].Username).toLowerCase() === username.toLowerCase()) {
        return { success: false, message: 'Username already exists.' };
      }
    }

    var now = nowIso_();
    appendRecord_('Users', {
      ID: generateUserId_(),
      Username: username,
      Password: password,
      FullName: fullName,
      Role: role,
      Phone: phone,
      Status: 'active',
      CreatedAt: now,
      UpdatedAt: now
    });

    return { success: true, message: 'Account created successfully.' };
  });
}

function getUsers(token) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief']);

    var users = getRecords_('Users').map(mapUserRecordToClient_);
    return { success: true, users: users };
  });
}

function updateUser(token, data) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief']);
    data = data || {};

    if (!data.id) {
      return { success: false, message: 'User ID is required.' };
    }

    var existing = findRecordById_('Users', data.id);
    if (!existing) {
      return { success: false, message: 'User not found.' };
    }

    var updated = cloneRecord_(existing);
    updated.FullName = trimString_(data.fullName) || existing.FullName;
    updated.Role = trimString_(data.role) || existing.Role;
    updated.Phone = trimString_(data.phone) || existing.Phone;
    updated.Status = trimString_(data.status) || existing.Status || 'active';
    updated.UpdatedAt = nowIso_();

    if (trimString_(data.password)) {
      updated.Password = trimString_(data.password);
    }

    writeRecord_('Users', existing._rowNumber, updated);
    return { success: true, message: 'User updated successfully.', user: mapUserRecordToClient_(updated) };
  });
}

function deleteUser(token, userId) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief']);

    if (!userId) {
      return { success: false, message: 'User ID is required.' };
    }

    var existing = findRecordById_('Users', userId);
    if (!existing) {
      return { success: false, message: 'User not found.' };
    }

    if (String(existing.Username) === String(user.username)) {
      return { success: false, message: 'You cannot delete the currently logged-in user.' };
    }

    deleteRecordById_('Users', userId);
    return { success: true, message: 'User deleted successfully.' };
  });
}

function getCases(token) {
  return runSafely_(function() {
    var user = requireUser_(token);
    var records = getVisibleCaseRecords_(user);
    var cases = records.map(mapCaseRecordToClient_);
    return { success: true, cases: cases };
  });
}

function createCase(token, data) {
  return runSafely_(function() {
    var user = requireUser_(token);
    data = data || {};

    var validation = validateCasePayload_(data);
    if (!validation.success) {
      return validation;
    }

    var now = nowIso_();
    var caseId = generateCaseId_();
    appendRecord_('Cases', {
      ID: caseId,
      Type: trimString_(data.type),
      Priority: trimString_(data.priority) || 'medium',
      Status: trimString_(data.status) || 'new',
      ResidentName: trimString_(data.resident.name),
      ResidentIdNumber: trimString_(data.resident.idNumber),
      ResidentPhone: trimString_(data.resident.phone),
      ResidentLocation: trimString_(data.resident.location),
      Description: trimString_(data.description),
      CreatedAt: now,
      UpdatedAt: now,
      CreatedBy: user.username,
      UpdatedBy: user.username
    });

    return {
      success: true,
      message: 'Case created successfully.',
      caseId: caseId
    };
  });
}

function updateCase(token, data) {
  return runSafely_(function() {
    var user = requireUser_(token);
    data = data || {};

    if (!data.id) {
      return { success: false, message: 'Case ID is required.' };
    }

    var existing = findRecordById_('Cases', data.id);
    if (!existing) {
      return { success: false, message: 'Case not found.' };
    }

    if (user.role === 'resident' && String(existing.CreatedBy) !== String(user.username)) {
      return { success: false, message: 'You can only update your own cases.' };
    }

    var validation = validateCasePayload_(data);
    if (!validation.success) {
      return validation;
    }

    var updated = cloneRecord_(existing);
    updated.Type = trimString_(data.type);
    updated.Priority = trimString_(data.priority) || existing.Priority || 'medium';
    updated.Status = trimString_(data.status) || existing.Status || 'new';
    updated.ResidentName = trimString_(data.resident.name);
    updated.ResidentIdNumber = trimString_(data.resident.idNumber);
    updated.ResidentPhone = trimString_(data.resident.phone);
    updated.ResidentLocation = trimString_(data.resident.location);
    updated.Description = trimString_(data.description);
    updated.UpdatedAt = nowIso_();
    updated.UpdatedBy = user.username;

    writeRecord_('Cases', existing._rowNumber, updated);

    // If status is resolved, move to ResolvedCases sheet
    if (updated.Status === 'resolved') {
      try {
        deleteRecord_('Cases', existing._rowNumber);
        addRecord_('ResolvedCases', updated);
      } catch (e) {
        console.error('Failed to move case to ResolvedCases', e);
      }
    }

    return {
      success: true,
      message: 'Case updated successfully.' + (updated.Status === 'resolved' ? ' Moved to Archive.' : ''),
      caseItem: mapCaseRecordToClient_(updated)
    };
  });
}

function deleteCase(token, caseId) {
  return runSafely_(function() {
    var user = requireUser_(token);

    if (!caseId) {
      return { success: false, message: 'Case ID is required.' };
    }

    var existing = findRecordById_('Cases', caseId);
    if (!existing) {
      return { success: false, message: 'Case not found.' };
    }

    if (user.role === 'resident') {
      return { success: false, message: 'Residents cannot delete cases.' };
    }

    deleteRecordById_('Cases', caseId);
    return { success: true, message: 'Case deleted successfully.' };
  });
}

function getDashboardStats(token) {
  return runSafely_(function() {
    var user = requireUser_(token);
    var records = getVisibleCaseRecords_(user);
    var dashboardData = buildDashboardData_(records);

    return {
      success: true,
      stats: dashboardData.stats,
      recentCases: dashboardData.recentCases
    };
  });
}

function getDocuments(token) {
  return runSafely_(function() {
    requireUser_(token);

    var records = getRecords_('Documents');
    var documents = records.map(function(record) {
      var mapped = mapDocumentRecordToClient_(record);
      mapped.hasFile = !!record.FileData;
      delete mapped.fileData; // Optimization: Don't send heavy data in list
      return mapped;
    }).sort(function(a, b) {
      return dateValue_(b.createdAt) - dateValue_(a.createdAt);
    });

    return { success: true, documents: documents };
  });
}

function getDocumentDetail(token, id) {
  return runSafely_(function() {
    requireUser_(token);
    if (!id) return { success: false, message: 'ID required.' };
    var record = findRecordById_('Documents', id);
    if (!record) return { success: false, message: 'Document not found.' };
    return { success: true, document: mapDocumentRecordToClient_(record) };
  });
}

function addDocument(token, data) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief', 'desk_officer']);
    data = data || {};

    if (!trimString_(data.category) || !trimString_(data.documentType)) {
      return { success: false, message: 'Document category and type are required.' };
    }

    var now = nowIso_();
    var documentId = generateDocumentId_();

    appendRecord_('Documents', {
      ID: documentId,
      Category: trimString_(data.category) || 'general',
      DocumentType: trimString_(data.documentType) || '',
      ResidentName: trimString_(data.residentName) || '',
      IDNumber: trimString_(data.idNumber) || '',
      Details: trimString_(data.details) || '',
      FileData: data.fileData || '',
      CreatedAt: now,
      UpdatedAt: now,
      CreatedBy: user.username,
      UpdatedBy: user.username
    });

    return { success: true, message: 'Document added successfully.', documentId: documentId };
  });
}

function updateDocument(token, data) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief', 'desk_officer']);
    data = data || {};

    if (!data.id) {
      return { success: false, message: 'Document ID is required.' };
    }

    var existing = findRecordById_('Documents', data.id);
    if (!existing) {
      return { success: false, message: 'Document not found.' };
    }

    var updated = cloneRecord_(existing);
    updated.Category = trimString_(data.category) || existing.Category || 'general';
    updated.DocumentType = trimString_(data.documentType) || existing.DocumentType || '';
    updated.ResidentName = trimString_(data.residentName) || existing.ResidentName || '';
    updated.IDNumber = trimString_(data.idNumber) || existing.IDNumber || '';
    updated.Details = trimString_(data.details) || existing.Details || '';
    updated.FileData = data.fileData || existing.FileData || '';
    updated.UpdatedAt = nowIso_();
    updated.UpdatedBy = user.username;

    writeRecord_('Documents', existing._rowNumber, updated);

    return {
      success: true,
      message: 'Document updated successfully.',
      documentItem: mapDocumentRecordToClient_(updated)
    };
  });
}

function deleteDocument(token, documentId) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief', 'desk_officer']);

    if (!documentId) {
      return { success: false, message: 'Document ID is required.' };
    }

    var existing = findRecordById_('Documents', documentId);
    if (!existing) {
      return { success: false, message: 'Document not found.' };
    }

    deleteRecordById_('Documents', documentId);
    return { success: true, message: 'Document deleted successfully.' };
  });
}

function getSettings(token) {
  if (token) {
    var user = getCachedUser_(token);
    if (!user) {
      return { success: false, message: 'Session expired. Please log in again.' };
    }
  }

  return { success: true, settings: getSettingsObject_() };
}

function updateSettings(token, data) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief']);
    data = data || {};

    var settings = getSettingsObject_();
    settings.officeName = trimString_(data.officeName) || settings.officeName;
    settings.officeAddress = trimString_(data.officeAddress) || settings.officeAddress;
    settings.location = trimString_(data.location) || settings.location;
    settings.logoUrl = trimString_(data.logoUrl) || '';
    settings.footerText = trimString_(data.footerText) || settings.footerText;
    settings.smsNotifications = toBoolean_(data.smsNotifications, settings.smsNotifications);
    settings.emailNotifications = toBoolean_(data.emailNotifications, settings.emailNotifications);
    settings.theme = trimString_(data.theme) || settings.theme || DEFAULT_SETTINGS.Theme;

    saveSettingsObject_(settings, user.username);
    return { success: true, message: 'Settings updated successfully.', settings: settings };
  });
}

function getBootstrapData(token) {
  return runSafely_(function() {
    var user = requireUser_(token);
    var caseRecords = getVisibleCaseRecords_(user);
    var dashboardData = buildDashboardData_(caseRecords);
    var documents = getRecords_('Documents')
      .sort(function(a, b) {
        return dateValue_(b.CreatedAt) - dateValue_(a.CreatedAt);
      })
      .map(mapDocumentRecordToClient_);

    return {
      success: true,
      settings: getSettingsObject_(),
      cases: caseRecords.map(mapCaseRecordToClient_),
      documents: documents,
      stats: dashboardData.stats,
      recentCases: dashboardData.recentCases,
      announcements: getRecords_('Announcements').sort(function(a, b) {
        return dateValue_(b.CreatedAt) - dateValue_(a.CreatedAt);
      }).map(mapAnnouncementRecordToClient_)
    };
  });
}

function getVisibleCaseRecords_(user) {
  var activeRecords = getRecords_('Cases');
  var resolvedRecords = getRecords_('ResolvedCases');
  var records = activeRecords.concat(resolvedRecords);

  if (user.role === 'resident') {
    records = records.filter(function(record) {
      return String(record.CreatedBy || '') === String(user.username);
    });
  }

  records.sort(function(a, b) {
    return dateValue_(b.CreatedAt) - dateValue_(a.CreatedAt);
  });

  return records;
}

function validateCasePayload_(data) {
  if (!data || !data.resident) {
    return { success: false, message: 'Case details are required.' };
  }

  if (!trimString_(data.type)) {
    return { success: false, message: 'Case type is required.' };
  }

  if (!trimString_(data.resident.name)) {
    return { success: false, message: 'Resident name is required.' };
  }

  if (!trimString_(data.resident.phone)) {
    return { success: false, message: 'Resident phone is required.' };
  }

  if (!trimString_(data.description)) {
    return { success: false, message: 'Case description is required.' };
  }

  return { success: true };
}

function buildDashboardData_(records) {
  var total = records.length;
  var pending = 0;
  var resolved = 0;

  for (var i = 0; i < records.length; i++) {
    var status = String(records[i].Status || '').toLowerCase();
    if (status === 'resolved') {
      resolved++;
    }
    if (status === 'new' || status === 'pending' || status === 'in_progress') {
      pending++;
    }
  }

  return {
    stats: {
      total: total,
      pending: pending,
      resolved: resolved,
      resolutionRate: total ? Math.round((resolved / total) * 100) : 0
    },
    recentCases: records.slice(0, 5).map(mapCaseRecordToClient_)
  };
}

function getSettingsObject_() {
  var record = getRecords_('Settings')[0] || {};

  return {
    officeName: trimString_(record.OfficeName) || DEFAULT_SETTINGS.OfficeName,
    officeAddress: trimString_(record.OfficeAddress) || DEFAULT_SETTINGS.OfficeAddress,
    location: trimString_(record.Location) || DEFAULT_SETTINGS.Location,
    logoUrl: trimString_(record.LogoUrl) || DEFAULT_SETTINGS.LogoUrl,
    footerText: trimString_(record.FooterText) || DEFAULT_SETTINGS.FooterText,
    smsNotifications: toBoolean_(record.SmsNotifications, DEFAULT_SETTINGS.SmsNotifications),
    emailNotifications: toBoolean_(record.EmailNotifications, DEFAULT_SETTINGS.EmailNotifications),
    theme: trimString_(record.Theme) || DEFAULT_SETTINGS.Theme,
    apiUrl: trimString_(record.ApiUrl) || ''
  };
}

function saveSettingsObject_(settings, updatedBy) {
  writeRecord_('Settings', 2, {
    ID: 'SETTINGS001',
    OfficeName: settings.officeName,
    OfficeAddress: settings.officeAddress,
    Location: settings.location,
    LogoUrl: settings.logoUrl,
    FooterText: settings.footerText,
    SmsNotifications: settings.smsNotifications,
    EmailNotifications: settings.emailNotifications,
    Theme: settings.theme || DEFAULT_SETTINGS.Theme,
    ApiUrl: trimString_(settings.apiUrl) || '',
    UpdatedAt: nowIso_(),
    UpdatedBy: updatedBy || 'system'
  });
}

function getCachedUser_(token) {
  if (!token) {
    return null;
  }

  var userString = CacheService.getScriptCache().get(token);
  return userString ? JSON.parse(userString) : null;
}

function requireUser_(token) {
  initializeSheets_();
  var user = getCachedUser_(token);
  if (!user) {
    throw new Error('Session expired. Please log in again.');
  }
  return user;
}

function requireRole_(user, roles) {
  if (roles.indexOf(user.role) === -1) {
    throw new Error('You are not authorized to perform this action.');
  }
}

function mapUserRecordToClient_(record) {
  return {
    id: String(record.ID || ''),
    username: String(record.Username || ''),
    fullName: String(record.FullName || ''),
    role: String(record.Role || 'resident'),
    phone: String(record.Phone || ''),
    status: String(record.Status || 'active')
  };
}

function mapCaseRecordToClient_(record) {
  return {
    id: String(record.ID || ''),
    type: String(record.Type || ''),
    priority: String(record.Priority || 'medium'),
    status: String(record.Status || 'new'),
    resident: {
      name: String(record.ResidentName || ''),
      idNumber: String(record.ResidentIdNumber || ''),
      phone: String(record.ResidentPhone || ''),
      location: String(record.ResidentLocation || '')
    },
    description: String(record.Description || ''),
    createdAt: toIsoString_(record.CreatedAt),
    updatedAt: toIsoString_(record.UpdatedAt),
    createdBy: String(record.CreatedBy || ''),
    updatedBy: String(record.UpdatedBy || '')
  };
}

function mapDocumentRecordToClient_(record) {
  return {
    id: String(record.ID || ''),
    category: String(record.Category || 'general'),
    documentType: String(record.DocumentType || ''),
    residentName: String(record.ResidentName || ''),
    idNumber: String(record.IDNumber || ''),
    details: String(record.Details || ''),
    fileData: String(record.FileData || ''),
    createdAt: toIsoString_(record.CreatedAt),
    updatedAt: toIsoString_(record.UpdatedAt),
    createdBy: String(record.CreatedBy || ''),
    updatedBy: String(record.UpdatedBy || '')
  };
}

function getSheet_(sheetName) {
  return SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);
}

function getHeaders_(sheetName) {
  return SHEET_SCHEMAS[sheetName].slice();
}

function getRecords_(sheetName) {
  var sheet = getSheet_(sheetName);
  var data = sheet.getDataRange().getValues();
  var records = [];

  if (data.length < 2) {
    return records;
  }

  var headers = data[0];
  for (var rowIndex = 1; rowIndex < data.length; rowIndex++) {
    if (isBlankRow_(data[rowIndex])) {
      continue;
    }

    var record = {};
    for (var columnIndex = 0; columnIndex < headers.length; columnIndex++) {
      record[headers[columnIndex]] = data[rowIndex][columnIndex];
    }
    record._rowNumber = rowIndex + 1;
    records.push(record);
  }

  return records;
}

function appendRecord_(sheetName, record) {
  var sheet = getSheet_(sheetName);
  sheet.appendRow(buildRow_(sheetName, record));
}

function writeRecord_(sheetName, rowNumber, record) {
  var sheet = getSheet_(sheetName);
  sheet.getRange(rowNumber, 1, 1, SHEET_SCHEMAS[sheetName].length).setValues([buildRow_(sheetName, record)]);
}

function buildRow_(sheetName, record) {
  var headers = getHeaders_(sheetName);
  return headers.map(function(header) {
    var value = record[header];
    return value === undefined || value === null ? '' : value;
  });
}

function findRecordById_(sheetName, id) {
  var records = getRecords_('' + sheetName);
  for (var i = 0; i < records.length; i++) {
    if (String(records[i].ID) === String(id)) {
      return records[i];
    }
  }
  return null;
}

function deleteRecordById_(sheetName, id) {
  var record = findRecordById_(sheetName, id);
  if (!record) {
    return false;
  }

  getSheet_(sheetName).deleteRow(record._rowNumber);
  return true;
}

function runSafely_(callback) {
  try {
    return callback();
  } catch (error) {
    return {
      success: false,
      message: error && error.message ? error.message : 'An unexpected error occurred.'
    };
  }
}

function isBlankRow_(row) {
  for (var i = 0; i < row.length; i++) {
    if (row[i] !== '' && row[i] !== null) {
      return false;
    }
  }
  return true;
}

function cloneRecord_(record) {
  var clone = {};
  for (var key in record) {
    if (record.hasOwnProperty(key)) {
      clone[key] = record[key];
    }
  }
  return clone;
}

function trimString_(value) {
  if (value === null || value === undefined) {
    return '';
  }
  return String(value).replace(/^\s+|\s+$/g, '');
}

function nowIso_() {
  return new Date().toISOString();
}

function toIsoString_(value) {
  if (!value) {
    return '';
  }
  if (Object.prototype.toString.call(value) === '[object Date]' && !isNaN(value.getTime())) {
    return value.toISOString();
  }
  return String(value);
}

function dateValue_(value) {
  if (!value) {
    return 0;
  }
  var parsed = new Date(value);
  return isNaN(parsed.getTime()) ? 0 : parsed.getTime();
}

function toBoolean_(value, fallback) {
  if (value === true || value === false) {
    return value;
  }
  if (value === 'true' || value === 'TRUE') {
    return true;
  }
  if (value === 'false' || value === 'FALSE') {
    return false;
  }
  return fallback;
}

function generateUserId_() {
  return 'USR' + new Date().getTime().toString().slice(-6);
}

function generateCaseId_() {
  return 'KAAS-' + new Date().getTime().toString(36).toUpperCase();
}

function generateDocumentId_() {
  return 'DOC-' + new Date().getTime().toString(36).toUpperCase();
}

function isApiRequest_(e) {
  return !!(e && getRequestParams_(e).action);
}

function handleApiRequest_(e) {
  var params = getRequestParams_(e);
  var callback = sanitizeCallback_(params.callback);
  var result = dispatchApiAction_(params);
  return createApiResponse_(result, callback);
}

function dispatchApiAction_(params) {
  var action = trimString_(params.action);
  var payload = parsePayload_(params.payload);
  var token = trimString_(params.token || payload.token);
  var id = trimString_(params.id || payload.id);

  switch (action) {
    case 'ping':
      return {
        success: true,
        connected: true,
        appName: APP_METADATA.appName,
        version: APP_METADATA.version,
        timestamp: nowIso_()
      };
    case 'initializeSheets':
      return initializeSheets();
    case 'login':
      return login(trimString_(params.username || payload.username), trimString_(params.password || payload.password));
    case 'validateToken':
      return validateToken(token);
    case 'logout':
      return logout(token);
    case 'signup':
      return signup(payload);
    case 'getUsers':
      return getUsers(token);
    case 'updateUser':
      return updateUser(token, payload);
    case 'deleteUser':
      return deleteUser(token, id);
    case 'getCases':
      return getCases(token);
    case 'createCase':
      return createCase(token, payload);
    case 'updateCase':
      return updateCase(token, payload);
    case 'deleteCase':
      return deleteCase(token, id);
    case 'getDashboardStats':
      return getDashboardStats(token);
    case 'getBootstrapData':
      return getBootstrapData(token);
    case 'getDocuments':
      return getDocuments(token);
    case 'getDocumentDetail':
      return getDocumentDetail(token, id);
    case 'addDocument':
      return addDocument(token, payload);
    case 'updateDocument':
      return updateDocument(token, payload);
    case 'deleteDocument':
      return deleteDocument(token, id);
    case 'getSettings':
      return getSettings(token);
    case 'updateSettings':
      return updateSettings(token, payload);
    case 'getAnnouncements':
      return getAnnouncements(token);
    case 'createAnnouncement':
      return createAnnouncement(token, payload);
    case 'deleteAnnouncement':
      return deleteAnnouncement(token, id);
    case 'validateSuperAdmin':
      return validateSuperAdmin(payload);
    default:
      return { success: false, message: 'Unknown API action.' };
  }
}

function getRequestParams_(e) {
  var params = {};

  if (e && e.parameter) {
    for (var key in e.parameter) {
      if (e.parameter.hasOwnProperty(key)) {
        params[key] = e.parameter[key];
      }
    }
  }

  if (e && e.postData && e.postData.contents) {
    try {
      var contents = e.postData.contents;
      // If it looks like JSON, parse it
      if (contents.indexOf('{') === 0) {
        var postPayload = JSON.parse(contents);
        if (postPayload && typeof postPayload === 'object') {
          for (var payloadKey in postPayload) {
            if (postPayload.hasOwnProperty(payloadKey) && params[payloadKey] === undefined) {
              params[payloadKey] = postPayload[payloadKey];
            }
          }
        }
      } else if (contents.indexOf('payload=') === 0) {
        // Handle application/x-www-form-urlencoded manually if needed
        var parts = contents.split('&');
        parts.forEach(function(part) {
          var pair = part.split('=');
          var k = decodeURIComponent(pair[0]);
          var v = decodeURIComponent(pair[1] || '');
          params[k] = v;
        });
      } else if (!params.payload) {
        params.payload = contents;
      }
    } catch (error) {
      if (!params.payload) {
        params.payload = e.postData.contents;
      }
    }
  }

  return params;
}

function parsePayload_(payload) {
  if (!payload) {
    return {};
  }

  if (typeof payload === 'object') {
    return payload;
  }

  try {
    return JSON.parse(payload);
  } catch (error) {
    return {};
  }
}

function createApiResponse_(result, callback) {
  var json = JSON.stringify(result || {});

  if (callback) {
    return ContentService
      .createTextOutput(callback + '(' + json + ');')
      .setMimeType(ContentService.MimeType.JAVASCRIPT);
  }

  return ContentService
    .createTextOutput(json)
    .setMimeType(ContentService.MimeType.JSON);
}

function sanitizeCallback_(callback) {
  callback = trimString_(callback);
  if (!callback) {
    return '';
  }

  return /^[A-Za-z_$][0-9A-Za-z_$\.]*$/.test(callback) ? callback : '';
}

function getAnnouncements(token) {
  return runSafely_(function() {
    requireUser_(token);
    var records = getRecords_('Announcements');
    var announcements = records.map(function(record) {
      var mapped = mapAnnouncementRecordToClient_(record);
      // Optional: Don't send heavy file data in list if not needed
      // but usually announcements aren't that many, so it's fine for now.
      return mapped;
    }).sort(function(a, b) {
      return dateValue_(b.createdAt) - dateValue_(a.createdAt);
    });

    return { success: true, announcements: announcements };
  });
}

function createAnnouncement(token, payload) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief', 'desk_officer']);

    var now = nowIso_();
    var id = 'ANN-' + new Date().getTime().toString(36).toUpperCase();
    
    appendRecord_('Announcements', {
      ID: id,
      Type: trimString_(payload.type) || 'text',
      Title: trimString_(payload.title),
      Content: trimString_(payload.content),
      Category: trimString_(payload.category) || 'general',
      FileData: payload.fileData || '',
      MimeType: payload.mimeType || '',
      CreatedAt: now,
      UpdatedAt: now,
      CreatedBy: user.username,
      UpdatedBy: user.username
    });

    return { success: true, message: 'Announcement posted successfully.', id: id };
  });
}

function updateAnnouncement(token, payload) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief', 'desk_officer']);

    if (!payload.id) {
      return { success: false, message: 'Announcement ID is required.' };
    }

    var existing = findRecordById_('Announcements', payload.id);
    if (!existing) {
      return { success: false, message: 'Announcement not found.' };
    }

    var updated = cloneRecord_(existing);
    updated.Type = trimString_(payload.type) || existing.Type;
    updated.Title = trimString_(payload.title) || existing.Title;
    updated.Content = trimString_(payload.content) || existing.Content;
    updated.Category = trimString_(payload.category) || existing.Category;
    updated.FileData = payload.fileData || existing.FileData;
    updated.MimeType = payload.mimeType || existing.MimeType;
    updated.UpdatedAt = nowIso_();
    updated.UpdatedBy = user.username;

    writeRecord_('Announcements', existing._rowNumber, updated);

    return { success: true, message: 'Announcement updated successfully.' };
  });
}

function deleteAnnouncement(token, id) {
  return runSafely_(function() {
    var user = requireUser_(token);
    requireRole_(user, ['chief', 'desk_officer']);
    
    if (!id) {
      return { success: false, message: 'Announcement ID is required.' };
    }

    var existing = findRecordById_('Announcements', id);
    if (!existing) {
      return { success: false, message: 'Announcement not found.' };
    }

    deleteRecordById_('Announcements', id);
    return { success: true, message: 'Announcement deleted successfully.' };
  });
}

function mapAnnouncementRecordToClient_(record) {
  return {
    id: String(record.ID || ''),
    type: String(record.Type || 'text'),
    title: String(record.Title || ''),
    content: String(record.Content || ''),
    category: String(record.Category || 'general'),
    fileData: String(record.FileData || ''),
    mimeType: String(record.MimeType || ''),
    createdAt: toIsoString_(record.CreatedAt),
    updatedAt: toIsoString_(record.UpdatedAt),
    createdBy: String(record.CreatedBy || ''),
    updatedBy: String(record.UpdatedBy || '')
  };
}

function validateSuperAdmin(data) {
  var user = data.username;
  var pass = data.password;
  if (user === 'administrator' && pass === 'admin0001') {
    return { success: true, message: 'Super Admin Access Granted' };
  }
  return { success: false, message: 'Invalid Super Admin credentials' };
}
